version: 2
jobs:
  build:
    docker:
      - image: circleci/node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "npm installing build"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "test running!"
      - run: npm install
      - run: npm test
  helloThere:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello world!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - helloThere
      - test: 
          requires:
            - helloThere
      